camera.kitchen_view:
  entity_picture: /api/camera_proxy/camera.kitchen_view?token=bb893335dd1a3406b26c6c1f36ea25e450998cc7aad107dc4e7ba8e4d7d4fed3


media_player.kodi_tv:
  friendly_name: Kodi

input_boolean:
  kodi_tv_state:

media_player:
- platform: universal
  name: Kodi TV
  state_template: >
    {% if is_state('media_player.kodi', 'idle') and is_state('input_boolean.kodi_tv_state', 'off') %}
    off
    {% else %}
    {{ states('media_player.kodi') }}
    {% endif %}
  children:
    - media_player.kodi
  commands:
    turn_on:
      service: media_player.turn_on
      target:
        entity_id: media_player.kodi
    turn_off:
      service: media_player.turn_off
      target:
        entity_id: media_player.kodi
  attributes:
    is_volume_muted: media_player.kodi|is_volume_muted
    volume_level: media_player.kodi|volume_level

- platform: kodi
  name: Kodi
  host: 192.168.1.10
  turn_on_action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kodi_tv_state
  - service: media_player.kodi_call_method
    target:
      entity_id: media_player.kodi
    data:
      method: Addons.ExecuteAddon
      addonid: script.json-cec
      params:
        command: activate
  turn_off_action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.kodi_tv_state
  - service: media_player.media_stop
    target:
      entity_id: media_player.kodi
  - service: media_player.kodi_call_method
    target:
      entity_id: media_player.kodi
    data:
      method: Addons.ExecuteAddon
      addonid: script.json-cec
      params:
        command: standby

automation:
- alias: "Turn on the TV when Kodi is activated"
  trigger:
    platform: state
    entity_id: media_player.kodi_tv
    from: "off"
    to: "playing"
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.kodi_tv

- alias: "Turn off the TV when Kodi is in idle > 15 min"
  trigger:
    platform: state
    entity_id: media_player.kodi_tv
    to: "idle"
    for:
      minutes: 15
  action:
  - service: media_player.turn_off
    target:
      entity_id: media_player.kodi_tv
